### ISSUE TITLE
Addon error when building after adding in ember-cli-foundation-sass

### ISSUE THREAD

**Issue by visualjeff** [nadavshatz/ember-cli-foundation-sass#25]
My environment is:
* ubuntu 14.04
* ember-cli version: 0.2.2
* node: 1.6.3
* npm: 2.7.4

I created a new ember-cli project.  Success!   The new project builds fine.
I addon ember-cli-foundation-sass.  I choose to use jquery 2.x.x (my bower.json file reflects this).
I run an ember build command.
I receive the following error:

> File: bower_components/foundation/scss/foundation/components/_forms.scss (336)
> expected a variable name (e.g. $x) or ')' for the parameter list for url
> Error: expected a variable name (e.g. $x) or ')' for the parameter list for url
>     at options.error (/home/jeffg/WebstormProjects/sasstest/node_modules/ember-cli- sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:261:32)

I've tried with Foundation 5.5.0 and 5.4.7 and I receive the same error.

Any ideas as why I'm unable to compile Foundation's _forms.scss?

**Comment by blisst** [comment]
I am having the same error
node: 0.10.36
npm: 2.1.11
ember-cli: 0.2.0-beta.1
ember-cli-foundation-sass: 1.1.0

**Comment by Globegitter** [comment]
Ahh that might be a bug with libsass itself. Which version of node-sass is it installing?

Yep found it: https://github.com/sass/libsass/issues/1059

**Comment by jessiahr** [comment]
I am having the same error, what was the solution for this issue?

**Comment by visualjeff** [comment]
Back down the version of broccoli-sass being used to 0.3.3 in your package.json.

**Comment by jessiahr** [comment]
When I back down the broccoli-sass version I get a build error with node-sass dependency (Module did not self-register.) which is related to this issue -> https://github.com/sass/node-sass/issues/653. Am I the only one having this issue?

**Comment by visualjeff** [comment]
Did u perform npm install after changing the version?

**Comment by jessiahr** [comment]
I did and when it tries to install node-sass@1.2.3 as a dependency of broccoli-sass@0.3.3 I get a build error: `Error: Module did not self-register.`  

I am relatively new to npm (primarily a ruby dev) but It seems like using 0.3.3 locks me in with using the old v of node-sass that has a issue that is not  fixed until v2.0.1. Am I missing an obvious solution?

**Comment by visualjeff** [comment]
Here is what my coworker did to resolve this issue on his project:

The current version of libssass(3.2.0 beta 5) that is included in ember-cli-sass(installed as part of ember-cli-foundation-sass) has bug with foundation scss. I am able to get it to compile and build using ember-cli-sass v 3.1.0.

**Comment by Globegitter** [comment]
@visualjeff do you know if ember-cli-sass 4.0.0-beta.4 work? will update then?

**Comment by visualjeff** [comment]
In a fresh ember-cli project...  

$ ember install ember-cli-sass     
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
__No compatible version found: node-sass@'>=3.0.0 <4.0.0'__
Valid install targets:
["0.9.4-rc1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0-alpha","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4-rc1","0.9.4","0.9.5-rc1","0.9.5","0.9.6","1.0.0","1.0.1","1.0.2-alpha","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","2.0.0-beta","2.0.0","2.0.1","3.0.0-alpha.0","3.0.0-beta.2","3.0.0-beta.3","3.0.0-beta.4","2.1.0","2.1.1","3.0.0-beta.5"]

Error: No compatible version found: node-sass@'>=3.0.0 <4.0.0'
Valid install targets:
["0.9.4-rc1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0-alpha","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4-rc1","0.9.4","0.9.5-rc1","0.9.5","0.9.6","1.0.0","1.0.1","1.0.2-alpha","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","2.0.0-beta","2.0.0","2.0.1","3.0.0-alpha.0","3.0.0-beta.2","3.0.0-beta.3","3.0.0-beta.4","2.1.0","2.1.1","3.0.0-beta.5"]

    at installTargetsError (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/lib/cache/add-named.js:262:12)
    at next (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/lib/cache/add-named.js:241:17)
    at setData (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/lib/cache/add-named.js:218:5)
    at RES (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/node_modules/inflight/inflight.js:23:14)
    at f (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/node_modules/once/once.js:17:25)
    at saved (/home/jeffg/WebstormProjects/sassy/node_modules/ember-cli/node_modules/npm/lib/cache/caching-client.js:173:7)
    at FSReqWrap.oncomplete (fs.js:77:15)

**Comment by visualjeff** [comment]
npm install --save-dev ember-cli-sass sings the same song.

**Comment by Globegitter** [comment]
I published a new version locking ember-cli-sass to 3.1.0 for now. If that works we can close this issue. Thanks for checking!

**Comment by asurtih** [comment]
I am working with @visualjeff. As @visualjeff had mentioned I am able to get everything build and run using ember-cli-sass v3.1.0 However when I bring up the app in Firefox, I get error saying "Style sheet could not be loaded. Http://localhost:4200/tree_merger-tmp_dest_dir-FQkHWggR.tmp/app/styhles/ap.scss". The app succesfully launch with no ill effect on styling. However, when I go to console I can see the following error/warning:

Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. vendor.css:4
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. vendor.css:4
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. pattern-library.css:256
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. pattern-library.css:277
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. pattern-library.css:421
Error in parsing value for 'cursor'.  Declaration dropped. pattern-library.css:1612
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. pattern-library.css:2872
Error in parsing value for 'cursor'.  Declaration dropped. pattern-library.css:3056
Error in parsing value for 'cursor'.  Declaration dropped. pattern-library.css:3060
Unknown property 'touch-action'.  Declaration dropped. pattern-library.css:3762
Unknown property 'touch-action'.  Declaration dropped. pattern-library.css:3772
Error in parsing value for 'cursor'.  Declaration dropped. pattern-library.css:3803
Expected color but found 'none'.  Expected end of value but found 'none'.  Error in parsing value for 'border'.  Declaration dropped. pattern-library.css:3825
Unknown property 'touch-action'.  Declaration dropped. pattern-library.css:3828
Expected end of value but found '0'.  Error in parsing value for 'margin-bottom'.  Declaration dropped. pattern-library.css:4077
Unknown property 'user-select'.  Declaration dropped. pattern-library.css:4112
Expected end of value but found '""'.  Error in parsing value for 'box-shadow'.  Declaration dropped. pattern-library.css:4521
Error in parsing value for 'transition'.  Declaration dropped. pattern-library.css:4758
Expected media feature name but found 'touch-enabled'. localhost:4200:1
Expected media feature name but found '-webkit-touch-enabled'. localhost:4200:1
Expected media feature name but found '-o-touch-enabled'. localhost:4200:1
Expected media feature name but found '-ms-touch-enabled'. localhost:4200:1
Expected media feature name but found 'modernizr'. localhost:4200:1
Unknown property '-moz-opacity'.  Declaration dropped. localhost:4200
Error in parsing value for 'background-image'.  Declaration dropped. localhost:4200
Expected color but found 'left'.  Error in parsing value for 'background-image'.  Declaration dropped.

Is this problem with foundation scss or firefox problem?

**Comment by visualjeff** [comment]
Latest update to the SASS Saga...

Adi and I tested our project using both ember-cli 0.2.2 and 0.2.3 (the project does include sass code).

I ran the following commands on our project:
>  npm install --save-dev ember-cli-foundation-sass
>  npm install --save-dev ember-cli-sass@3.1.0

My package.json shows:

```
"devDependencies": {                                                                                                                                                                                                               
    "ember-cli": "0.2.3", 
    ...                                                                                                                                                                                              
    "ember-cli-foundation-sass": "^1.1.1",                                                                                             
    "ember-cli-sass": "3.1.0",
     ...                                                                                                         
}                          
```

Built and started project.  Site worked perfect.  SASS compiled and worked as expected.

I hope this helps.

**Comment by asurtih** [comment]
I found that the error/warning that I saw in firefox is foundation issue. In regards to this specific error: "Style sheet could not be loaded. Http://localhost:4200/tree_merger-tmp_dest_dir-FQkHWggR.tmp/app/styhles/ap.scss", I found that by using ember-cli-sass v3.3.1, this error message goes away. @Globegitter, can you published a new version locking ember-cli-sass to 3.3.1?

**Comment by thsdrouot** [comment]
Hi guys,

Running : 
- node v0.12.2
- ember-cli v0.2.3
- ember install ember-cli-foundation-sass, it means in my package.json :    
    "ember-cli-foundation-sass": "^1.1.1",                                                                                             
    "ember-cli-sass": "3.1.0",
and in bower.json:
    "foundation": "~5.5.1"

I still get the following :

`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

Any ideas? Thanks

**Comment by asurtih** [comment]
Try it with ember-cli-sass v3.3.1.

**Comment by thsdrouot** [comment]
Already done : same error... 
I will try again. I might do a mistake.

**Comment by thsdrouot** [comment]
It works with ember-cli-sass v3.3.1!

Thanks

**Comment by thsdrouot** [comment]
Hi guys,

We still have again an error with node-sass when installing Ember-CLI-Foundation-Sass. May you have an idea to resolve this persisting problem? Thanks in advance.

**Comment by nadavshatz** [comment]
Sorry for never responding, the repo has changed hands.
I'm closing all old issues as they are very old.

Please open a new issue if you are experiencing issues with the new version.
